repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
    - id: isort
      additional_dependencies: ['toml==0.10.2']

-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      additional_dependencies: ['pep8-naming==0.11.1', 'flake8-mutable==1.2.0']
      args: ['--max-line-length=120', '--ignore=E203,E501,N806,N816,N817,W503']
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    - id: pydocstyle
      additional_dependencies: ['toml==0.10.2']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      additional_dependencies: ['types-python-dateutil==2.8.3', 'pydantic==1.9.0']
